services:
  globalping-traceroute:
    build: .
    container_name: globalping-traceroute-app
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=globalping_traceroute.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      # Add your Globalping API token here if you have one
      # - GLOBALPING_API_TOKEN=your_api_token_here
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount logs directory if you want to persist logs
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 